### ISSUE TITLE
Implement and test ControlUnit component

### ISSUE THREAD

**Issue by angloth** [tsea83-g34/TSEA83_Hardware#10]

**Comment by angloth** [comment]
@angloth Implement and test control logic for ALU, RegisterFile and DataForwarding.

@Henkecool Implement and test control logic for DataMemory, (VGA memory).

@jullinator Implement and test control logic for ProgramMemory and WriteBackLogic.

**Comment by angloth** [comment]
Control Signals for RegisterFile and DataForwarding are now finished.

**Comment by angloth** [comment]
WriteBackLogic and DataMemory control signals are now implemented.

**Comment by angloth** [comment]
Todo:
- Implement VideoMemory control signals
- Finish ALU control signals
- Double check Programmemory control signals
- Write some testbench for ControlUnit

**Comment by angloth** [comment]
Implemented control signals for video memory and programmemory.

**Comment by jullinator** [comment]
> Todo:
> 
> * Implement VideoMemory control signals
> * Finish ALU control signals
> * Double check Programmemory control signals
> * Write some testbench for ControlUnit

I can start with the testbench for ControlUnit

**Comment by angloth** [comment]
Ok good, I'm working on finishing ALU (#18) and control signals for ALU.

**Comment by angloth** [comment]
Control signals for all components have been implemented. Now just need to test them which @jullinator will do for now

**Comment by angloth** [comment]
Completed  for now. Will reopen again later if we have bugs,
