### ISSUE TITLE
Fix data writing bug

### ISSUE THREAD

**Issue by Henkecool** [tsea83-g34/TSEA83_Hardware#65]

**Comment by angloth** [comment]
Data seems to be writing to the wrong address @Henkecool

**Comment by angloth** [comment]
Loading and storing data in words seems to working when address is % 4.

**Comment by angloth** [comment]
Found that the assemblern coded sizes HALF and BYTE incorrectly, this might have been the reason for the bug.

**Comment by angloth** [comment]
LOAD / STORE seems to be working better since the fix to size parsing. Check if larger programs such as rainbow.asm works.

**Comment by angloth** [comment]
Close for now as it seems to be working correctly
